using BuildTool.Generators;
using BuildTool.Models;

namespace BuildTool.Tests;

/// <summary>
/// Smoke tests for ModuleApiHeaderGenerator.
/// API headers are generated to {projectRoot}/Intermediate/Generated/{Module}API.generated.h.
/// </summary>
public static class ModuleApiHeaderGeneratorTest
{
    public static void Run()
    {
        Console.WriteLine("=== ModuleApiHeaderGenerator Smoke Tests ===");
        Console.WriteLine();

        TestSingleModuleGeneration();
        TestHeaderOnlyModuleSkipped();
        TestMacroCaseConversion();
        TestIdempotent();
        TestMultipleModules();

        Console.WriteLine();
        Console.WriteLine("=== All tests passed ===");
    }

    /// <summary>
    /// Generate API header for a single module, verify content.
    /// </summary>
    private static void TestSingleModuleGeneration()
    {
        Console.WriteLine("[Test 1] Single module: correct header content");

        string projectRoot = CreateTempProjectRoot();
        string moduleDir = CreateTempModuleDir("Core");
        try
        {
            var modules = new Dictionary<string, ModuleRules>
            {
                ["Core"] = new() { ModuleName = "Core", ModuleDirectory = moduleDir },
            };

            var generator = new ModuleApiHeaderGenerator();
            var result = generator.Generate(modules, projectRoot);

            Assert(result.Success, $"Expected success, got error: {result.Error}");
            Assert(result.GeneratedCount == 1, $"GeneratedCount: expected 1, got {result.GeneratedCount}");

            string outputPath = Path.Combine(projectRoot, "Intermediate", "Generated", "CoreAPI.generated.h");
            Assert(File.Exists(outputPath), $"Expected file at {outputPath}");

            string content = File.ReadAllText(outputPath);
            Assert(content.Contains("#pragma once"), "Missing #pragma once");
            Assert(content.Contains("#include \"HAL/Platform.h\""), "Missing Platform.h include");
            Assert(content.Contains("defined(CORE_EXPORTS)"), "Missing defined(CORE_EXPORTS)");
            Assert(content.Contains("#define CORE_API DLLEXPORT"), "Missing DLLEXPORT define");
            Assert(content.Contains("#define CORE_API DLLIMPORT"), "Missing DLLIMPORT define");
            Assert(content.Contains("Auto-generated by EnigmaEngine BuildTool"), "Missing auto-gen comment");

            Console.WriteLine("  PASSED");
        }
        finally
        {
            CleanupTempDir(projectRoot);
            CleanupTempDir(moduleDir);
        }
    }

    /// <summary>
    /// Header-only modules should be skipped entirely.
    /// </summary>
    private static void TestHeaderOnlyModuleSkipped()
    {
        Console.WriteLine("[Test 2] Header-only module: skipped");

        string projectRoot = CreateTempProjectRoot();
        string moduleDir = CreateTempModuleDir("JsonLib");
        try
        {
            var modules = new Dictionary<string, ModuleRules>
            {
                ["JsonLib"] = new()
                {
                    ModuleName = "JsonLib",
                    ModuleDirectory = moduleDir,
                    IsHeaderOnly = true,
                },
            };

            var generator = new ModuleApiHeaderGenerator();
            var result = generator.Generate(modules, projectRoot);

            Assert(result.Success, $"Expected success, got error: {result.Error}");
            Assert(result.GeneratedCount == 0, $"GeneratedCount: expected 0, got {result.GeneratedCount}");
            Assert(result.SkippedCount == 0, $"SkippedCount: expected 0, got {result.SkippedCount}");

            string outputPath = Path.Combine(projectRoot, "Intermediate", "Generated", "JsonLibAPI.generated.h");
            Assert(!File.Exists(outputPath), "Header-only module should not have API header");

            Console.WriteLine("  PASSED");
        }
        finally
        {
            CleanupTempDir(projectRoot);
            CleanupTempDir(moduleDir);
        }
    }

    /// <summary>
    /// Module name case conversion: ArcadeGameplay -> ARCADEGAMEPLAY.
    /// </summary>
    private static void TestMacroCaseConversion()
    {
        Console.WriteLine("[Test 3] Macro case conversion: ArcadeGameplay -> ARCADEGAMEPLAY");

        string projectRoot = CreateTempProjectRoot();
        string moduleDir = CreateTempModuleDir("ArcadeGameplay");
        try
        {
            var modules = new Dictionary<string, ModuleRules>
            {
                ["ArcadeGameplay"] = new()
                {
                    ModuleName = "ArcadeGameplay",
                    ModuleDirectory = moduleDir,
                },
            };

            var generator = new ModuleApiHeaderGenerator();
            var result = generator.Generate(modules, projectRoot);

            Assert(result.Success, $"Expected success, got error: {result.Error}");

            string content = File.ReadAllText(
                Path.Combine(projectRoot, "Intermediate", "Generated", "ArcadeGameplayAPI.generated.h"));
            Assert(content.Contains("ARCADEGAMEPLAY_EXPORTS"), "Missing ARCADEGAMEPLAY_EXPORTS");
            Assert(content.Contains("ARCADEGAMEPLAY_API"), "Missing ARCADEGAMEPLAY_API");

            Console.WriteLine("  PASSED");
        }
        finally
        {
            CleanupTempDir(projectRoot);
            CleanupTempDir(moduleDir);
        }
    }

    /// <summary>
    /// Running Generate twice should skip on second run (content unchanged).
    /// </summary>
    private static void TestIdempotent()
    {
        Console.WriteLine("[Test 4] Idempotent: second run skips unchanged files");

        string projectRoot = CreateTempProjectRoot();
        string moduleDir = CreateTempModuleDir("Engine");
        try
        {
            var modules = new Dictionary<string, ModuleRules>
            {
                ["Engine"] = new() { ModuleName = "Engine", ModuleDirectory = moduleDir },
            };

            var generator = new ModuleApiHeaderGenerator();

            // First run: should write
            var result1 = generator.Generate(modules, projectRoot);
            Assert(result1.Success, $"First run failed: {result1.Error}");
            Assert(result1.GeneratedCount == 1, $"First run GeneratedCount: expected 1, got {result1.GeneratedCount}");

            // Second run: should skip
            var result2 = generator.Generate(modules, projectRoot);
            Assert(result2.Success, $"Second run failed: {result2.Error}");
            Assert(result2.GeneratedCount == 0, $"Second run GeneratedCount: expected 0, got {result2.GeneratedCount}");
            Assert(result2.SkippedCount == 1, $"Second run SkippedCount: expected 1, got {result2.SkippedCount}");

            Console.WriteLine("  PASSED");
        }
        finally
        {
            CleanupTempDir(projectRoot);
            CleanupTempDir(moduleDir);
        }
    }

    /// <summary>
    /// Generate for multiple modules at once.
    /// </summary>
    private static void TestMultipleModules()
    {
        Console.WriteLine("[Test 5] Multiple modules: all generated");

        string projectRoot = CreateTempProjectRoot();
        string tempDir1 = CreateTempModuleDir("Core");
        string tempDir2 = CreateTempModuleDir("Engine");
        string tempDir3 = CreateTempModuleDir("Launch");
        try
        {
            var modules = new Dictionary<string, ModuleRules>
            {
                ["Core"] = new() { ModuleName = "Core", ModuleDirectory = tempDir1 },
                ["Engine"] = new() { ModuleName = "Engine", ModuleDirectory = tempDir2 },
                ["Launch"] = new() { ModuleName = "Launch", ModuleDirectory = tempDir3 },
            };

            var generator = new ModuleApiHeaderGenerator();
            var result = generator.Generate(modules, projectRoot);

            Assert(result.Success, $"Expected success, got error: {result.Error}");
            Assert(result.GeneratedCount == 3, $"GeneratedCount: expected 3, got {result.GeneratedCount}");

            string genDir = Path.Combine(projectRoot, "Intermediate", "Generated");
            Assert(File.Exists(Path.Combine(genDir, "CoreAPI.generated.h")), "Missing CoreAPI.generated.h");
            Assert(File.Exists(Path.Combine(genDir, "EngineAPI.generated.h")), "Missing EngineAPI.generated.h");
            Assert(File.Exists(Path.Combine(genDir, "LaunchAPI.generated.h")), "Missing LaunchAPI.generated.h");

            Console.WriteLine("  PASSED");
        }
        finally
        {
            CleanupTempDir(projectRoot);
            CleanupTempDir(tempDir1);
            CleanupTempDir(tempDir2);
            CleanupTempDir(tempDir3);
        }
    }

    private static string CreateTempProjectRoot()
    {
        string dir = Path.Combine(Path.GetTempPath(), "EnigmaTest", $"Project_{Guid.NewGuid():N}");
        Directory.CreateDirectory(dir);
        return dir;
    }

    private static string CreateTempModuleDir(string moduleName)
    {
        string tempDir = Path.Combine(Path.GetTempPath(), "EnigmaTest", $"Module_{moduleName}_{Guid.NewGuid():N}");
        Directory.CreateDirectory(Path.Combine(tempDir, "Public"));
        Directory.CreateDirectory(Path.Combine(tempDir, "Private"));
        return tempDir;
    }

    private static void CleanupTempDir(string dir)
    {
        try { if (Directory.Exists(dir)) Directory.Delete(dir, recursive: true); }
        catch { /* Best effort */ }
    }

    private static void Assert(bool condition, string message)
    {
        if (!condition)
            throw new Exception($"Assertion failed: {message}");
    }
}
