using System.Text;
using BuildTool.Analysis;
using BuildTool.Models;

namespace BuildTool.Generators;

/// <summary>
/// Generates CMakeLists.txt from parsed module rules and dependency resolution results.
/// Produces library targets controlled by BUILD_SHARED_LIBS (SHARED when ON, STATIC when OFF),
/// with proper dependency linking, include paths, and {MODULE}_EXPORTS macro definitions.
/// </summary>
public sealed class CMakeGenerator
{
    /// <summary>
    /// Result of CMake generation.
    /// </summary>
    public sealed class GenerateResult
    {
        /// <summary>Whether generation succeeded.</summary>
        public required bool Success { get; init; }

        /// <summary>Generated CMakeLists.txt content (empty if failed).</summary>
        public string Content { get; init; } = string.Empty;

        /// <summary>Error message if generation failed.</summary>
        public string? Error { get; init; }

        public static GenerateResult Ok(string content) => new() { Success = true, Content = content };
        public static GenerateResult Fail(string error) => new() { Success = false, Error = error };
    }

    /// <summary>
    /// Generate CMakeLists.txt content from parsed module rules and resolved dependencies.
    /// </summary>
    /// <param name="projectName">Project name for the CMake project() declaration.</param>
    /// <param name="modules">All parsed module rules (keyed by module name).</param>
    /// <param name="resolveResult">Dependency resolution result with build order.</param>
    /// <param name="projectRootPath">Absolute path to the project root directory.</param>
    /// <param name="targetRules">Optional target rules. When provided with Type=Game,
    /// modules in ExtraModuleNames are generated as executables.</param>
    /// <param name="configuration">Build configuration (Debug/DebugGame/Development/Shipping/Test).
    /// Controls optimization levels, debug symbols, and macro definitions.</param>
    /// <param name="platform">Target platform string for DLL naming (default "Win64").</param>
    /// <returns>A <see cref="GenerateResult"/> with the generated content or error.</returns>
    public GenerateResult Generate(
        string projectName,
        IReadOnlyDictionary<string, ModuleRules> modules,
        DependencyResolver.ResolveResult resolveResult,
        string projectRootPath,
        TargetRules? targetRules = null,
        BuildConfiguration configuration = BuildConfiguration.Development,
        string platform = "Win64")
    {
        if (!resolveResult.Success)
        {
            return GenerateResult.Fail(
                $"Cannot generate CMake: dependency resolution failed. {resolveResult.Error}");
        }

        if (modules.Count == 0)
        {
            return GenerateResult.Fail("Cannot generate CMake: no modules provided.");
        }

        var sb = new StringBuilder(4096);

        // Normalize path separators for CMake (always forward slashes)
        var cmakeRootPath = NormalizePath(projectRootPath);

        WriteHeader(sb, projectName);
        WriteGlobalSettings(sb);
        WriteBuildConfigurationDefinitions(sb, configuration);
        WriteSourceRoot(sb, cmakeRootPath);

        // Determine which modules are executable targets (from TargetRules.ExtraModuleNames)
        var executableModules = new HashSet<string>(StringComparer.Ordinal);
        if (targetRules is { Type: TargetType.Game })
        {
            foreach (var name in targetRules.ExtraModuleNames)
            {
                executableModules.Add(name);
            }
        }

        // Generate module targets in topological order (dependencies first)
        var libraryModuleNames = new List<string>();
        string? executableModuleName = null;

        foreach (var moduleName in resolveResult.BuildOrder)
        {
            if (!modules.TryGetValue(moduleName, out var rules))
            {
                continue;
            }

            var isExecutable = executableModules.Contains(moduleName);
            WriteModuleTarget(sb, rules, cmakeRootPath, isExecutable, projectName, configuration, platform);

            if (isExecutable)
                executableModuleName = moduleName;
            else if (!rules.IsHeaderOnly)
                libraryModuleNames.Add(moduleName);
        }

        // Monolithic (static) linking support
        WriteMonolithicLinkingBlock(sb, executableModuleName, libraryModuleNames);

        return GenerateResult.Ok(sb.ToString());
    }

    /// <summary>
    /// Write CMake header: minimum version and project declaration.
    /// </summary>
    private static void WriteHeader(StringBuilder sb, string projectName)
    {
        sb.AppendLine("# Auto-generated by EnigmaEngine BuildTool");
        sb.AppendLine("# Do not edit manually - changes will be overwritten.");
        sb.AppendLine();
        sb.AppendLine("cmake_minimum_required(VERSION 3.28)");
        sb.AppendLine($"project({projectName} LANGUAGES CXX)");
    }

    /// <summary>
    /// Write global CMake settings: C++ standard, output directories.
    /// Uses C++23 as the base standard (highest officially supported by CMake/MSVC),
    /// then adds compiler-specific flags for C++26 draft features.
    /// </summary>
    private static void WriteGlobalSettings(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("# C++ Standard (C++23 base + C++26 draft features via compiler flags)");
        sb.AppendLine("set(CMAKE_CXX_STANDARD 23)");
        sb.AppendLine("set(CMAKE_CXX_STANDARD_REQUIRED ON)");
        sb.AppendLine("set(CMAKE_CXX_EXTENSIONS OFF)");
        sb.AppendLine();
        sb.AppendLine("# Enable C++26 draft features per compiler");
        sb.AppendLine("if(MSVC)");
        sb.AppendLine("    add_compile_options(/std:c++latest /Zc:preprocessor)");
        sb.AppendLine("elseif(CMAKE_CXX_COMPILER_ID MATCHES \"GNU|Clang\")");
        sb.AppendLine("    add_compile_options(-std=c++2c)");
        sb.AppendLine("endif()");
        sb.AppendLine();
        sb.AppendLine("# Shared library output directories");
        sb.AppendLine("set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Binaries)");
        sb.AppendLine("set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Binaries)");
        sb.AppendLine("set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/Intermediate)");
    }

    /// <summary>
    /// Write build-configuration-specific compile definitions, optimization levels,
    /// and debug symbol settings.
    ///
    /// Configuration matrix (REQ-002):
    ///   | Config      | MSVC Opt | GCC Opt | Debug Symbols | Key Macros                          |
    ///   |-------------|----------|---------|---------------|-------------------------------------|
    ///   | Debug       | /Od      | -O0     | Yes           | ENIGMA_BUILD_DEBUG=1                |
    ///   | DebugGame   | /O1      | -O1     | Yes           | ENIGMA_BUILD_DEBUGGAME=1            |
    ///   | Development | /O1      | -O1     | Yes           | ENIGMA_BUILD_DEVELOPMENT=1          |
    ///   | Shipping    | /O2      | -O3     | No            | ENIGMA_BUILD_SHIPPING=1, NDEBUG     |
    ///   | Test        | /O2      | -O3     | Yes           | ENIGMA_BUILD_TEST=1, NDEBUG         |
    ///
    /// Shipping strips Verbose/Debug logs, removes check/checkf, simplifies ensure.
    /// Test is like Shipping optimization but retains debug symbols and console commands.
    /// </summary>
    private static void WriteBuildConfigurationDefinitions(StringBuilder sb, BuildConfiguration configuration)
    {
        sb.AppendLine();
        sb.AppendLine($"# ── Build Configuration: {configuration} ──");

        // Configuration identification macro (exactly one is defined per build)
        var configMacro = configuration switch
        {
            BuildConfiguration.Debug       => "ENIGMA_BUILD_DEBUG=1",
            BuildConfiguration.DebugGame   => "ENIGMA_BUILD_DEBUGGAME=1",
            BuildConfiguration.Development => "ENIGMA_BUILD_DEVELOPMENT=1",
            BuildConfiguration.Shipping    => "ENIGMA_BUILD_SHIPPING=1",
            BuildConfiguration.Test        => "ENIGMA_BUILD_TEST=1",
            _ => throw new ArgumentOutOfRangeException(nameof(configuration))
        };
        sb.AppendLine($"add_compile_definitions({configMacro})");

        // NDEBUG for release-like configurations (disables standard assert())
        if (configuration is BuildConfiguration.Shipping or BuildConfiguration.Test)
        {
            sb.AppendLine("add_compile_definitions(NDEBUG)");
        }

        // Optimization and debug symbol settings
        sb.AppendLine();
        WriteOptimizationSettings(sb, configuration);
    }

    /// <summary>
    /// Write per-compiler optimization flags and debug symbol settings.
    /// </summary>
    private static void WriteOptimizationSettings(StringBuilder sb, BuildConfiguration configuration)
    {
        // Determine MSVC settings
        var (msvcOpt, msvcDebug) = configuration switch
        {
            BuildConfiguration.Debug       => ("/Od", true),
            BuildConfiguration.DebugGame   => ("/O1", true),
            BuildConfiguration.Development => ("/O1", true),
            BuildConfiguration.Shipping    => ("/O2", false),
            BuildConfiguration.Test        => ("/O2", true),
            _ => throw new ArgumentOutOfRangeException(nameof(configuration))
        };

        // Determine GCC/Clang settings
        var (gccOpt, gccDebug) = configuration switch
        {
            BuildConfiguration.Debug       => ("-O0", true),
            BuildConfiguration.DebugGame   => ("-O1", true),
            BuildConfiguration.Development => ("-O1", true),
            BuildConfiguration.Shipping    => ("-O3", false),
            BuildConfiguration.Test        => ("-O3", true),
            _ => throw new ArgumentOutOfRangeException(nameof(configuration))
        };

        sb.AppendLine("# Optimization and debug symbols");
        sb.AppendLine("if(MSVC)");
        sb.AppendLine($"    add_compile_options({msvcOpt})");
        if (msvcDebug)
        {
            sb.AppendLine("    add_compile_options(/Zi)");
            sb.AppendLine("    add_link_options(/DEBUG)");
        }
        sb.AppendLine("elseif(CMAKE_CXX_COMPILER_ID MATCHES \"GNU|Clang\")");
        sb.AppendLine($"    add_compile_options({gccOpt})");
        if (gccDebug)
        {
            sb.AppendLine("    add_compile_options(-g)");
        }
        sb.AppendLine("endif()");
    }

    /// <summary>
    /// Write the source root variable for relative path resolution.
    /// </summary>
    private static void WriteSourceRoot(StringBuilder sb, string cmakeRootPath)
    {
        sb.AppendLine();
        sb.AppendLine("# Project source root");
        sb.AppendLine($"set(PROJECT_SOURCE_ROOT \"{cmakeRootPath}/Source\")");
    }

    /// <summary>
    /// Write a single module target. Dispatches to header-only (INTERFACE) or
    /// compiled (SHARED/executable) generation based on ModuleRules.IsHeaderOnly.
    /// </summary>
    private static void WriteModuleTarget(
        StringBuilder sb, ModuleRules rules, string cmakeRootPath, bool isExecutable,
        string projectName, BuildConfiguration configuration, string platform)
    {
        if (rules.IsHeaderOnly)
        {
            WriteHeaderOnlyModuleTarget(sb, rules, cmakeRootPath);
        }
        else
        {
            WriteCompiledModuleTarget(sb, rules, cmakeRootPath, isExecutable, projectName, configuration, platform);
        }
    }

    /// <summary>
    /// Write a header-only INTERFACE library target.
    /// No source files, no EXPORTS macro, no PRIVATE paths.
    /// Include paths are resolved from the module's absolute directory.
    /// </summary>
    private static void WriteHeaderOnlyModuleTarget(StringBuilder sb, ModuleRules rules, string cmakeRootPath)
    {
        var name = rules.ModuleName;

        sb.AppendLine();
        sb.AppendLine($"# ── Module: {name} (header-only) ──");
        sb.AppendLine();

        // INTERFACE library: no compiled sources
        sb.AppendLine($"add_library({name} INTERFACE)");
        sb.AppendLine();

        // Resolve include paths from the module's directory (absolute path)
        var moduleDir = !string.IsNullOrEmpty(rules.ModuleDirectory)
            ? NormalizePath(rules.ModuleDirectory)
            : $"${{PROJECT_SOURCE_ROOT}}/{name}";

        var interfacePaths = new List<string>();
        foreach (var path in rules.PublicIncludePaths)
        {
            var resolved = $"{moduleDir}/{path}";
            if (!interfacePaths.Contains(resolved))
            {
                interfacePaths.Add(resolved);
            }
        }

        // Fallback: if no explicit paths, expose the module root
        if (interfacePaths.Count == 0)
        {
            interfacePaths.Add(moduleDir);
        }

        sb.AppendLine($"target_include_directories({name}");
        sb.AppendLine("    INTERFACE");
        foreach (var p in interfacePaths)
        {
            sb.AppendLine($"        \"{p}\"");
        }
        sb.AppendLine(")");

        // Dependency linking (INTERFACE only)
        WriteHeaderOnlyDependencyLinks(sb, name, rules);
    }

    /// <summary>
    /// Write a compiled module target: library (type controlled by BUILD_SHARED_LIBS) or executable,
    /// sources glob, exports macro, include paths, dependency linking, and DLL output naming (REQ-015).
    ///
    /// DLL naming convention (only when BUILD_SHARED_LIBS=ON):
    ///   Development: {ProjectName}-{ModuleName}
    ///   Others:      {ProjectName}-{ModuleName}-{Platform}-{Config}
    /// </summary>
    private static void WriteCompiledModuleTarget(
        StringBuilder sb, ModuleRules rules, string cmakeRootPath, bool isExecutable,
        string projectName, BuildConfiguration configuration, string platform)
    {
        var name = rules.ModuleName;
        var upperName = name.ToUpperInvariant();
        // Use actual module directory if available (handles engine modules outside project Source/).
        // Fall back to PROJECT_SOURCE_ROOT/{name} for simple single-project layouts.
        var moduleSourceDir = !string.IsNullOrEmpty(rules.ModuleDirectory)
            ? NormalizePath(rules.ModuleDirectory)
            : $"${{PROJECT_SOURCE_ROOT}}/{name}";

        sb.AppendLine();
        sb.AppendLine($"# ── Module: {name} ──");
        sb.AppendLine();

        // Glob source files (CONFIGURE_DEPENDS: re-scan at build time when files change)
        sb.AppendLine($"file(GLOB_RECURSE {upperName}_SOURCES CONFIGURE_DEPENDS");
        sb.AppendLine($"    \"{moduleSourceDir}/*.cpp\"");
        sb.AppendLine($"    \"{moduleSourceDir}/*.h\"");
        sb.AppendLine($"    \"{moduleSourceDir}/*.hpp\"");
        sb.AppendLine(")");
        sb.AppendLine();

        // Add target: executable for Game entry modules, library for others
        // Library type is controlled by BUILD_SHARED_LIBS (SHARED when ON, STATIC when OFF)
        if (isExecutable)
        {
            sb.AppendLine($"add_executable({name} ${{{upperName}_SOURCES}})");
            // EXE output naming: {ProjectName} (Development) or {ProjectName}-{Platform}-{Config} (others)
            var exeOutputName = GetExecutableOutputName(projectName, configuration, platform);
            sb.AppendLine($"set_target_properties({name} PROPERTIES OUTPUT_NAME \"{exeOutputName}\")");
        }
        else
        {
            sb.AppendLine($"add_library({name} ${{{upperName}_SOURCES}})");
        }
        sb.AppendLine();

        // DLL output naming (REQ-015) - only for library targets in shared mode
        if (!isExecutable)
        {
            var outputName = GetOutputName(projectName, name, configuration, platform);
            sb.AppendLine($"if(BUILD_SHARED_LIBS)");
            sb.AppendLine($"    set_target_properties({name} PROPERTIES OUTPUT_NAME \"{outputName}\")");
            sb.AppendLine($"endif()");
            sb.AppendLine();
        }

        // Define {MODULE}_EXPORTS macro for DLL export/import (REQ-011)
        sb.AppendLine($"target_compile_definitions({name} PRIVATE {upperName}_EXPORTS)");

        // In static builds, define {MODULE}_STATIC_DEFINE so API macros resolve to empty
        // Only for library modules - executables don't export APIs
        if (!isExecutable)
        {
            sb.AppendLine($"if(NOT BUILD_SHARED_LIBS)");
            sb.AppendLine($"    target_compile_definitions({name} PUBLIC {upperName}_STATIC_DEFINE)");
            sb.AppendLine($"endif()");
        }
        sb.AppendLine();

        // Include paths
        WriteIncludePaths(sb, name, rules, moduleSourceDir, cmakeRootPath);

        // Dependency linking
        WriteDependencyLinks(sb, name, rules);
    }

    /// <summary>
    /// Compute the output name for a module target following REQ-015 DLL naming convention.
    ///
    ///   Development: {ProjectName}-{ModuleName}
    ///   Others:      {ProjectName}-{ModuleName}-{Platform}-{Config}
    /// </summary>
    private static string GetOutputName(
        string projectName, string moduleName, BuildConfiguration configuration, string platform)
    {
        if (configuration == BuildConfiguration.Development)
        {
            return $"{projectName}-{moduleName}";
        }

        return $"{projectName}-{moduleName}-{platform}-{configuration}";
    }

    /// <summary>
    /// Compute the output name for an executable target following UE naming convention.
    ///
    ///   Development: {ProjectName}
    ///   Others:      {ProjectName}-{Platform}-{Config}
    /// </summary>
    private static string GetExecutableOutputName(
        string projectName, BuildConfiguration configuration, string platform)
    {
        if (configuration == BuildConfiguration.Development)
        {
            return projectName;
        }

        return $"{projectName}-{platform}-{configuration}";
    }

    /// <summary>
    /// Write target_include_directories for a module.
    /// Always includes the module root. Adds Public/Private paths from ModuleRules.
    /// Adds Intermediate/Generated/ for auto-generated API headers.
    /// </summary>
    private static void WriteIncludePaths(
        StringBuilder sb, string name, ModuleRules rules, string moduleSourceDir, string cmakeRootPath)
    {
        // Collect PUBLIC include paths
        var publicPaths = new List<string>
        {
            $"{cmakeRootPath}/Intermediate/Generated",
            $"{moduleSourceDir}/Public"
        };
        foreach (var path in rules.PublicIncludePaths)
        {
            var normalized = $"{moduleSourceDir}/{path}";
            if (!publicPaths.Contains(normalized))
            {
                publicPaths.Add(normalized);
            }
        }

        // Collect PRIVATE include paths
        var privatePaths = new List<string> { $"{moduleSourceDir}/Private" };
        foreach (var path in rules.PrivateIncludePaths)
        {
            var normalized = $"{moduleSourceDir}/{path}";
            if (!privatePaths.Contains(normalized))
            {
                privatePaths.Add(normalized);
            }
        }

        sb.AppendLine($"target_include_directories({name}");
        sb.AppendLine("    PUBLIC");
        foreach (var p in publicPaths)
        {
            sb.AppendLine($"        \"{p}\"");
        }
        sb.AppendLine("    PRIVATE");
        foreach (var p in privatePaths)
        {
            sb.AppendLine($"        \"{p}\"");
        }
        sb.AppendLine(")");
    }

    /// <summary>
    /// Write target_link_libraries for a header-only INTERFACE module.
    /// INTERFACE targets can only use the INTERFACE keyword (not PUBLIC/PRIVATE).
    /// Both Public and Private dependencies are merged into INTERFACE.
    /// </summary>
    private static void WriteHeaderOnlyDependencyLinks(StringBuilder sb, string name, ModuleRules rules)
    {
        var allDeps = new List<string>();
        foreach (var dep in rules.PublicDependencyModuleNames)
        {
            if (!allDeps.Contains(dep))
                allDeps.Add(dep);
        }
        foreach (var dep in rules.PrivateDependencyModuleNames)
        {
            if (!allDeps.Contains(dep))
                allDeps.Add(dep);
        }

        if (allDeps.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine($"target_link_libraries({name}");
        sb.AppendLine("    INTERFACE");
        foreach (var dep in allDeps)
        {
            sb.AppendLine($"        {dep}");
        }
        sb.AppendLine(")");
    }

    /// <summary>
    /// Write target_link_libraries for a module's PUBLIC and PRIVATE dependencies.
    /// Only emits the block if there are dependencies to link.
    /// </summary>
    private static void WriteDependencyLinks(StringBuilder sb, string name, ModuleRules rules)
    {
        var hasPublic = rules.PublicDependencyModuleNames.Count > 0;
        var hasPrivate = rules.PrivateDependencyModuleNames.Count > 0;

        if (!hasPublic && !hasPrivate)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine($"target_link_libraries({name}");

        if (hasPublic)
        {
            sb.AppendLine("    PUBLIC");
            foreach (var dep in rules.PublicDependencyModuleNames)
            {
                sb.AppendLine($"        {dep}");
            }
        }

        if (hasPrivate)
        {
            sb.AppendLine("    PRIVATE");
            foreach (var dep in rules.PrivateDependencyModuleNames)
            {
                sb.AppendLine($"        {dep}");
            }
        }

        sb.AppendLine(")");
    }

    /// <summary>
    /// Write the monolithic (static) linking block.
    /// When BUILD_SHARED_LIBS is OFF, links all static library modules into the executable target.
    /// Uses WHOLE_ARCHIVE to prevent the linker from dead-stripping self-registering
    /// static objects (IMPLEMENT_MODULE entries) that have no external references.
    /// </summary>
    private static void WriteMonolithicLinkingBlock(
        StringBuilder sb, string? executableModuleName, List<string> libraryModuleNames)
    {
        if (executableModuleName is null || libraryModuleNames.Count == 0)
            return;

        sb.AppendLine();
        sb.AppendLine("# ── Monolithic (static) linking ──");
        sb.AppendLine("# WHOLE_ARCHIVE ensures IMPLEMENT_MODULE static registrars are not");
        sb.AppendLine("# dead-stripped by the linker (they have no external references).");
        sb.AppendLine("if(NOT BUILD_SHARED_LIBS)");
        sb.AppendLine($"    target_link_libraries({executableModuleName}");
        sb.AppendLine("        PRIVATE");
        foreach (var lib in libraryModuleNames)
        {
            sb.AppendLine($"            $<LINK_LIBRARY:WHOLE_ARCHIVE,{lib}>");
        }
        sb.AppendLine("    )");
        sb.AppendLine("endif()");
    }

    /// <summary>
    /// Normalize a file system path to use forward slashes (CMake convention).
    /// Removes trailing slashes.
    /// </summary>
    private static string NormalizePath(string path)
    {
        return path.TrimEnd('/', '\\').Replace('\\', '/');
    }
}
