// Copyright EnigmaEngine. All Rights Reserved.

namespace BuildTool.Generators;

using BuildTool.Models;
using BuildTool.Utils;

/// <summary>
/// Generates {ModuleName}API.h export macro headers for each non-header-only module.
/// Uses AtomicFileWriter for incremental writes (unchanged files are not overwritten).
/// </summary>
public sealed class ModuleApiHeaderGenerator
{
    public sealed class GenerateResult
    {
        /// <summary>Whether generation completed without errors.</summary>
        public required bool Success { get; init; }

        /// <summary>Error message if generation failed.</summary>
        public string? Error { get; init; }

        /// <summary>Number of header files written (new or updated).</summary>
        public int GeneratedCount { get; init; }

        /// <summary>Number of header files skipped (content unchanged).</summary>
        public int SkippedCount { get; init; }
    }

    /// <summary>
    /// Generate {Module}API.generated.h for each non-header-only module.
    /// Output goes to {projectRoot}/Intermediate/Generated/ to keep the source tree clean.
    /// Skips if file already exists with identical content.
    /// </summary>
    /// <param name="modules">All modules keyed by module name.</param>
    /// <param name="projectRoot">Absolute path to the project root (for Intermediate/Generated/ output).</param>
    /// <returns>Result with counts of generated and skipped files.</returns>
    public GenerateResult Generate(IReadOnlyDictionary<string, ModuleRules> modules, string projectRoot)
    {
        int generated = 0;
        int skipped = 0;

        try
        {
            string outputDir = Path.Combine(projectRoot, "Intermediate", "Generated");
            Directory.CreateDirectory(outputDir);

            foreach (var (name, rules) in modules)
            {
                // Skip header-only modules (no compiled code, no DLL export needed)
                if (rules.IsHeaderOnly)
                    continue;

                string macroPrefix = name.ToUpperInvariant();
                string content = GenerateHeaderContent(macroPrefix);
                string outputPath = Path.Combine(outputDir, $"{name}API.generated.h");

                var status = AtomicFileWriter.WriteIfChanged(outputPath, content);

                switch (status)
                {
                    case AtomicFileWriter.WriteStatus.Written:
                        generated++;
                        break;
                    case AtomicFileWriter.WriteStatus.Unchanged:
                        skipped++;
                        break;
                    case AtomicFileWriter.WriteStatus.Error:
                        return new GenerateResult
                        {
                            Success = false,
                            Error = $"Failed to write {outputPath}",
                            GeneratedCount = generated,
                            SkippedCount = skipped,
                        };
                }
            }

            return new GenerateResult
            {
                Success = true,
                GeneratedCount = generated,
                SkippedCount = skipped,
            };
        }
        catch (Exception ex)
        {
            return new GenerateResult
            {
                Success = false,
                Error = ex.Message,
                GeneratedCount = generated,
                SkippedCount = skipped,
            };
        }
    }

    /// <summary>
    /// Generate the C++ header content for a module API export macro.
    /// </summary>
    private static string GenerateHeaderContent(string macroPrefix)
    {
        return $"""
            // Auto-generated by EnigmaEngine BuildTool. DO NOT EDIT.
            #pragma once

            #include "HAL/Platform.h"

            #ifdef {macroPrefix}_STATIC_DEFINE
                #define {macroPrefix}_API
            #elif defined({macroPrefix}_EXPORTS)
                #define {macroPrefix}_API DLLEXPORT
            #else
                #define {macroPrefix}_API DLLIMPORT
            #endif
            """.Replace("            ", "") + Environment.NewLine;
    }
}
